name: Type check, test and build

on:
  push:
    branches:
      - main
    paths:
      - "client/**"
      - ".github/workflows/**"
  pull_request:
    branches:
      - main
    paths:
      - "client"
      - ".github/workflows/**"

jobs:
  typecheck_test_and_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install npm dependencies
        working-directory: client
        run: npm install

      - name: TypeScript type check
        working-directory: client
        run: npx tsc --noEmit

      - name: Run tests
        working-directory: client
        run: npx jest --passWithNoTests
